[project]
name = "bookmind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mehmet CAKMAK", email = "cakmakm541@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "fastapi>=0.141.1",
    "jinja2>=3.1.6",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.0",
    "langgraph>=1.2.11",
    "pymupdf>=1.28.2",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
bookmind = "bookmind:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
